---
title: "my-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(lab6package)

# dataset knapsack_objects included
knapsack_objects[1:10,]

# brute_force_knapsack
brute_force_knapsack(x = knapsack_objects[1:8,], W = 3500)
system.time(brute_force_knapsack(x = knapsack_objects[1:16,], W = 3500))
#(question 1.1.2)the time take to run algorithm for n=16 

# knapsack_dynamic
knapsack_dynamic(x = knapsack_objects[1:8,], W = 3500)
system.time(knapsack_dynamic(x = knapsack_objects[1:500,], W = 3500))
#(question 1.1.3)the time take to run algorithm for n=500

#greedy_knapsack
greedy_knapsack(x = knapsack_objects[1:8,], W = 3500)

#(question1.1.4) the time take to run algorithm for n=1000
suppressWarnings(RNGversion(min(as.character(getRversion()),"3.5.3")))
set.seed(42, kind = "Mersenne-Twister", normal.kind = "Inversion")
n <- 1000000
knapsack_objects_e6 <- data.frame(
  w=sample(1:4000, size = n, replace = TRUE),
  v=runif(n = n, 0, 10000)
)
system.time(greedy_knapsack(x = knapsack_objects_e6[1:1000000,], W = 3500))


#systemtime
system.time(brute_force_knapsack(x = knapsack_objects[1:18,], W = 3500))
system.time(knapsack_dynamic(x = knapsack_objects[1:18,], W = 3500))
system.time(greedy_knapsack(x = knapsack_objects[1:18,], W = 3500))

#optimize
knapsack_dynamic(x = knapsack_objects[1:16,], W = 3500)
brute_force_knapsack_optimize(x = knapsack_objects[1:16,], W = 3500)
brute_force_knapsack_parallel(x = knapsack_objects[1:16,], W = 3500, parallel = FALSE)
brute_force_knapsack_parallel(x = knapsack_objects[1:16,], W = 3500, parallel = TRUE)
#time
system.time(brute_force_knapsack_optimize(x = knapsack_objects[1:16,], W = 3500))
# ( for question 1.1.6)it is used to compare the brute force knapsacks to show different performances
system.time(brute_force_knapsack_parallel(x = knapsack_objects[1:16,], W = 3500, parallel = FALSE))
system.time(brute_force_knapsack_parallel(x = knapsack_objects[1:16,], W = 3500, parallel = TRUE))
#( for question1.1.8) it is used to compare the brute force knapsacks to show the different performances


```
